version: 2.1
orbs: 
  slack: circleci/slack@4.10.1

jobs:

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-dependances]
      - run:
          name: Build front-end
          command: |
             cd frontend
             npm install
             npm run build
           # exit 1
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-dependances
      - slack/notify:
          event: pass
          template: basic_success_1


  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-dependances]
      - run:
          name: Back-end build
          command: |
             cd backend
             npm install
             npm run build
            # exit 2
      - save_cache:
          paths: [backend/node_modules]
          key: backend-dependances
      - slack/notify:
          event: pass
          template: basic_success_1

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
         keys: [frontend-test]
      - run:
         name: Test frontend
         command: |
           cd frontend
           npm install
           npm run test
      - slack/notify:
          event: pass
          template: basic_success_1

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
         keys: [backend-test]
      - run:
         name: Test backend
         command: |
           cd backend
           npm install
           npm run test
      - slack/notify:
          event: pass
          template: basic_success_1

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
         keys: [frontend-scan]
      - run:
         name: Scan frontend for vulnerabilities
         command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - slack/notify:
          event: pass
          template: basic_success_1

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
         keys: [backend-scan]
      - run:
         name: Scan backend for vulnerabilities
         command: |
            cd backend
            npm install
            npm audit fix --force --audit-level=critical 
            npm audit fix --force --audit-level=critical 
            npm audit --audit-level=critical 
      - slack/notify:
          event: pass
          template: basic_success_1


workflows:
  default:
    jobs:
      - build-frontend:
         context: slack-secrets
      - build-backend:
         context: slack-secrets
      - test-frontend:
         requires:
           - build-frontend
         context: slack-secrets
      - test-backend:
         requires: 
           - build-backend
         context: slack-secrets
      - scan-backend:
          requires:
            - build-backend
          context: slack-secrets
      - scan-frontend:
          requires:
            - build-frontend
          context: slack-secrets
